{
  "artifact_3744882570": {
    "java_home": "extracted/jdk-26",
    "java_version_output": "openjdk 26-internal 2026-03-17\nOpenJDK Runtime Environment (build 26-internal-lahodaj-397ae3270ef6bcc2437023e2ebf7e5d48147bd6e)\nOpenJDK 64-Bit Server VM (build 26-internal-lahodaj-397ae3270ef6bcc2437023e2ebf7e5d48147bd6e, mixed mode, sharing)"
  },
  "status": "passed",
  "history": [],
  "datetime": "2025-08-13T13:13:36.603666+00:00",
  "url": "https://github.com/openjdk/jdk/pull/26758",
  "number": 26758,
  "title": "8365314: javac fails with an exception for erroneous source",
  "head_sha": "397ae3270ef6bcc2437023e2ebf7e5d48147bd6e",
  "run_url": "https://github.com/dougxc/openjdk-pr-canary/actions/runs/16938025745"
}